variables:
  Codeql.Enabled: true

trigger:
  batch: true
  branches:
    include:
      - main

jobs:
  - job: ComplianceJob
    strategy:
      matrix:
        windows:
          imageName: 'windows-latest'
    pool:
      vmImage: $(imageName)
    steps:
      - task: CredScan@3
        inputs:
          outputFormat: sarif
          debugMode: false

      - task: ComponentGovernanceComponentDetection@0
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'High'

      - task: PublishSecurityAnalysisLogs@3
        inputs:
          ArtifactName: 'CodeAnalysisLogs'
          ArtifactType: 'Container'

      - task: CodeQL3000Finalize@0
        condition: always()
